# Generated by Django 2.0.1 on 2018-01-11 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradingCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=11)),
                ('auto_sell', models.PositiveIntegerField(default=0)),
                ('stop_loss', models.PositiveIntegerField(default=0)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.Coin')),
            ],
        ),
    ]
