# Generated by Django 2.0.1 on 2018-01-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='id',
        ),
        migrations.AddField(
            model_name='coin',
            name='btc_price',
            field=models.DecimalField(decimal_places=8, default=0.00023, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradingcondition',
            name='btc_buy_price',
            field=models.DecimalField(decimal_places=8, default=0.00045, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingcondition',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
