# Generated by Django 2.0.1 on 2018-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_auto_20180111_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcondition',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
