# Generated by Django 2.0.1 on 2018-01-11 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_tradingcondition_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcondition',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
