# Generated by Django 2.0.1 on 2018-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradingcondition_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcondition',
            name='change',
            field=models.IntegerField(default=0),
        ),
    ]
