# Generated by Django 2.0.1 on 2018-01-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradingcondition_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcondition',
            name='earnings',
            field=models.DecimalField(decimal_places=8, default=1e-05, max_digits=20),
            preserve_default=False,
        ),
    ]
