# Generated by Django 2.0.1 on 2018-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_tradingcondition_earnings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingcondition',
            name='earnings',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
