# Generated by Django 2.0.1 on 2018-01-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_auto_20180111_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingcondition',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
