# Generated by Django 2.0.1 on 2018-01-11 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_auto_20180111_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingcondition',
            name='trader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.Trader'),
            preserve_default=False,
        ),
    ]
