# Generated by Django 2.0.1 on 2018-01-11 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_tradingcondition_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trader',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
