# Generated by Django 2.0.1 on 2018-01-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_tradingcondition_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingcondition',
            name='amount',
        ),
        migrations.AlterField(
            model_name='tradingcondition',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradingcondition',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=1e-06, max_digits=20),
            preserve_default=False,
        ),
    ]
