# Generated by Django 2.0.1 on 2018-01-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0019_auto_20180111_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='step_size',
            field=models.DecimalField(decimal_places=8, default=1e-08, max_digits=20),
        ),
    ]
