# Generated by Django 2.0.1 on 2018-01-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_coin_step_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='btc_price',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
    ]
