# Generated by Django 2.0.1 on 2018-01-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_auto_20180112_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='eth_balance',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='tradingcondition',
            name='market',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH')], default='BTC', max_length=3),
            preserve_default=False,
        ),
    ]
